### ISSUE TITLE
Parsing wrong files, break all hotkeys

### ISSUE THREAD

**Issue by max-mykhailenko** [subhaze/CSS-Extended#26]
I have some strange situation.

OS X 10.9.3
Sublime text 3 build 3059
Plugin configuration:

```
{
  "css_extension": [".less"]
}
```

I delete cache and add several .less files to it again. But plugin try parse css files from another folder. All files have UTF-8 encoding

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 263, in on_post_save_async
    callback.on_post_save_async(v)
  File "css_style_completions in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 62, in on_post_save_async
  File "style_parser in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 125, in parse_view
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 344: ordinal not in range(128)
PARSING FILE /Users/userName/web/in/css/bootstrap.css
PARSING FILE /Users/userName/web/in/css/in.css
PARSING FILE /Users/userName/web/in/css/bootstrap-responsive.css
```

UPDATE: Right click on LESS folder in sidebar menu, click on "Add LESS files to cache" and see in console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 263, in on_post_save_async
    callback.on_post_save_async(v)
  File "css_style_completions in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 62, in on_post_save_async
  File "style_parser in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 125, in parse_view
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 344: ordinal not in range(128)
PARSING FILE /Users/userName/web/in/css/bootstrap.css
PARSING FILE /Users/userName/web/in/css/in.css
PARSING FILE /Users/userName/web/in/css/bootstrap-responsive.css
PARSING FILE /Users/userName/web/source/less/backend.less
PARSING FILE /Users/userName/web/source/less/frontend.less
```

Why plugin parse CSS folder? Also plugin reparse all css and less files after save html file!

UPDATE

Breaks all Sublime hotkeys after that:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 263, in on_post_save_async
    callback.on_post_save_async(v)
  File "css_style_completions in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 62, in on_post_save_async
  File "style_parser in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 125, in parse_view
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 819: ordinal not in range(128)
PARSING FILE /Users/max/Work/Projects/kata.im/web/public/css/frontend.css
PARSING FILE /Users/max/Work/Projects/kata.im/web/source/css/frontend.css
Writing file /Users/max/Work/Projects/kata.im/inc/abstracts/frontend-header.php with encoding UTF-8 (atomic)
Writing file /Users/max/Work/Projects/kata.im/inc/abstracts/frontend-header.php with encoding UTF-8 (atomic)
PARSING SAVED VIEW
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 263, in on_post_save_async
    callback.on_post_save_async(v)
  File "css_style_completions in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 62, in on_post_save_async
  File "style_parser in /Users/max/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 125, in parse_view
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 852: ordinal not in range(128)
PARSING FILE /Users/max/Work/Projects/kata.im/web/public/css/frontend.css
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

How I can repair that?

**Comment by katerlouis** [comment]
Don't know if I should make another issue for this, since I get the same error.
My css folder contains 6 *.less files which I try to cache via on css-folder in sidebar.
I get this error 5 times (at different positions though)
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)`

But one file passes the compiler: `debugging.less`
debugging.less does not have a single _intended mixin_ inside, which is probably why it passes?
Although in LESS a declaration of a class is a mixin by itself, I guess.

The strangest part now is, that I get completions for some mixins I **used** inside the debugging.less.

`.no-text-selection;` for instance. I just use it inside debugging.less and yet get it as an completion.
No declaration with `{ }` for this class. I just used it! 

1) What is happening here? (could it be my umlaut comments, since I'm german?)
2) Would you be so kind and help me to get the other 5 files running?
3) Is there an option to only get auto completion for _"actual"_ mixins alá `.mixin()` wether with parameter or not.


Thanks so much.
I'll be a wizard with this plugin up and running.

**Comment by subhaze** [comment]
I'd say another issue, sadly all free/opensource items I've worked on in the past are way at the back of priorities for me ATM and not sure when they'll get bumped up. So... PR are very welcomed and I'll try to keep up with them.
