### ISSUE TITLE
CSS Extended Completations Menu Disabled

### ISSUE THREAD

**Issue by rubol** [subhaze/CSS-Extended#39]
Hello , 

I have been facing this problem for a while now, I tried changing my sublime build version but no luck. Right Now I am using Sublime 3 Build 3065 on a Fedora 21 System. I tried copying the default package settings to user package settings still no luck. I am still unable to enable that menu option in my sidebar.

This is my console LOG:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "01-ssl-linux in /home/rubol/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package", line 26, in <module>
NameError: name 'e' is not defined
reloading plugin 0_package_control_loader.02-bz2
reloading plugin CSS Extended Completions.cache
reloading plugin CSS Extended Completions.commands
reloading plugin CSS Extended Completions.completions
reloading plugin CSS Extended Completions.css_style_completions
reloading plugin CSS Extended Completions.extended_css_completions
reloading plugin CSS Extended Completions.location
reloading plugin CSS Extended Completions.project
reloading plugin CSS Extended Completions.settings
reloading plugin CSS Extended Completions.style_parser
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin CSSLint.CSSLint
reloading plugin CSSLint.version_file_checker
reloading plugin Emmet.emmet-plugin
loaded 1172 snippets
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Xdebug Client.main
reloading plugin SFTP.SFTP
SFTP: enabling custom linux ssl module
SFTP: _ssl module import error - libssl.so.1.0.0: cannot open shared object file: No such file or directory
SFTP: _ssl module import error - libssl.so.1.0.0: cannot open shared object file: No such file or directory
SFTP: _ssl module import error - libssl.so.1.0.0: cannot open shared object file: No such file or directory
plugins loaded
CSSLint is a .sublime-package; Verifying required files.
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2014-12-29 19:34:20, next run at 2014-12-29 20:34:20 or after

Please help me fix this, as this is one of the most important plugin in sublime for me. Pardon me if this turn out to be a system specific issue.

Regards

**Comment by eviljonas** [comment]
I have same problem with Debian , I couldn't load directorys with css fliles .
someone knows what can I do ?

**Comment by natanfelles** [comment]
One solution here, with Debian Testing, was to add the absolute path of CSS files in the **css_style_completions.sublime-settings**

```json
{
	"load_external_files": [
		"/directories/bootstrap.css"
	],
}
``` 

Of course, it is not an "external file", but works.

![captura de tela de 2017-11-22 21-59-46](https://user-images.githubusercontent.com/3011423/33154589-8168b158-cfd0-11e7-96c6-f98fec4e8262.png)
