### ISSUE TITLE
Unicode seems to break parsing

### ISSUE THREAD

**Issue by katerlouis** [subhaze/CSS-Extended#53]
My css folder contains 6 *.less files which I try to cache via on css-folder in sidebar.
I get this error 5 times (at different positions though)
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)`
console:
```
PARSING FILE /Users/me/some/long/path/vars.less
Traceback (most recent call last):
  File "style_parser in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 114, in <lambda>
  File "style_parser in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/CSS Extended Completions.sublime-package", line 100, in parse_file
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 795: ordinal not in range(128)
```

But one file passes the compiler: debugging.less
debugging.less does not have a single intended mixin inside, which is probably why it passes?
Although in LESS a declaration of a class is a mixin by itself, I guess.

The strangest part now is, that I get completions for some mixins I used inside the debugging.less.

.no-text-selection; for instance. I just use it inside debugging.less and yet get it as an completion.
No declaration with { } for this class. I just used it!

1) What is happening here? (could it be my umlaut comments, since I'm german?)
2) Would you be so kind and help me to get the other 5 files running?
3) Is there an option to only get auto completion for "actual" mixins alá .mixin() wether with parameter or not.

Thanks so much.
I'll be a wizard with this plugin up and running.

UPDATE:
Yap, one ö inside of debugging.less kills the parsing here aswell. What do we do now? :O

**Comment by katerlouis** [comment]
Okay; as mentioned in #50, this change brought the solution!
